import type { HypertensionIndicatorCategoryId } from '../types';

export interface HypertensionCatalogItem {
  id: string;
  label: string;
  category: HypertensionIndicatorCategoryId;
  referenceRange: string;
  clinicalMeaning: string;
  retestCycle: string;
  isCoreForHypertension: boolean;
  priority: 'high' | 'medium' | 'low';
  unit?: string;
  screeningFields?: (keyof import('../types').HypertensionScreeningRecord)[];
  checkupPaths?: string[];
}

export const HYPERTENSION_INDICATOR_CATEGORIES = [
  { id: 'bp_vascular' as const, label: '血压与血管评估', sortOrder: 1 },
  { id: 'target_organ' as const, label: '靶器官损伤筛查（心脑肾眼）', sortOrder: 2 },
  { id: 'metabolic_labs' as const, label: '代谢与实验室检查', sortOrder: 3 },
];

export const HYPERTENSION_SCREENING_CATALOG: HypertensionCatalogItem[] = [
  {
    id: 'office_bp',
    label: '诊室血压',
    category: 'bp_vascular',
    referenceRange: '一般<140/90 mmHg；合并糖尿病/CKD建议<130/80 mmHg',
    clinicalMeaning: '高血压诊断与随访的核心指标',
    retestCycle: '家庭自测每周2–3次；门诊每1–3个月',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmHg',
    screeningFields: ['sbp', 'dbp'],
    checkupPaths: ['checkup.basics.sbp', 'checkup.basics.dbp'],
  },
  {
    id: 'abpm',
    label: '动态血压监测（ABPM）',
    category: 'bp_vascular',
    referenceRange: '24h平均<130/80 mmHg；夜间下降10–20%',
    clinicalMeaning: '识别白大衣高血压、隐匿性高血压及夜间非杓型血压',
    retestCycle: '初诊疑诊时；调整方案后复测',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['abpmSummary', 'abpmDaySbp', 'abpmNightSbp'],
    checkupPaths: ['riskModelExtras.abpmSummary', 'riskModelExtras.abpmDaySbp'],
  },
  {
    id: 'carotid_us',
    label: '颈动脉彩超（斑块、内膜厚度）',
    category: 'bp_vascular',
    referenceRange: 'IMT<1.0 mm（因年龄调整）；无显著斑块',
    clinicalMeaning: '评估大动脉粥样硬化负荷，预测卒中风险',
    retestCycle: '每1–2年（有斑块者缩短）',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['carotidUltrasound', 'carotidImt', 'carotidPlaque'],
    checkupPaths: ['checkup.optional.carotidUltrasound', 'riskModelExtras.carotidImt'],
  },
  {
    id: 'echo',
    label: '心脏彩超（左心室肥厚、心功能）',
    category: 'bp_vascular',
    referenceRange: '无左室肥厚；EF≥50%',
    clinicalMeaning: '筛查高血压性心脏病及心功能受损',
    retestCycle: '每年或方案调整后',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['echoResult', 'lvh', 'ejectionFraction'],
    checkupPaths: ['checkup.optional.heartUltrasound', 'riskModelExtras.echoResult'],
  },
  {
    id: 'ecg',
    label: '心电图',
    category: 'bp_vascular',
    referenceRange: '窦性心律，无显著ST-T异常或左室高电压',
    clinicalMeaning: '筛查左室肥厚、心肌缺血及心律失常',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'medium',
    screeningFields: ['ecgResult'],
    checkupPaths: ['checkup.imagingBasic.ecg'],
  },
  {
    id: 'holter',
    label: '动态心电图（Holter）',
    category: 'bp_vascular',
    referenceRange: '无显著心律失常；无持续ST段改变',
    clinicalMeaning: '发现阵发性心律失常及无症状心肌缺血',
    retestCycle: '有症状或心电图异常时',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['holterResult'],
    checkupPaths: ['riskModelExtras.holterResult'],
  },
  {
    id: 'renal',
    label: '肾功能',
    category: 'target_organ',
    referenceRange: 'eGFR≥60 mL/min/1.73m²',
    clinicalMeaning: '评估高血压肾损害',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['creatinine', 'urea'],
    checkupPaths: ['checkup.labBasic.renal.creatinine', 'checkup.labBasic.renal.urea'],
  },
  {
    id: 'urine_albumin',
    label: '尿微量白蛋白/肌酐比值（UACR）',
    category: 'target_organ',
    referenceRange: 'UACR<30 mg/g',
    clinicalMeaning: '高血压肾损害早期标志',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mg/g',
    screeningFields: ['uacr', 'urineProtein'],
    checkupPaths: ['riskModelExtras.uacr', 'checkup.labBasic.urineRoutine.protein'],
  },
  {
    id: 'fundus',
    label: '眼底检查（高血压眼底病变）',
    category: 'target_organ',
    referenceRange: '无Keith-Wagener III–IV级改变',
    clinicalMeaning: '反映小动脉硬化程度，评估靶器官损害',
    retestCycle: '每年（控制不佳者每6个月）',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['fundusResult'],
    checkupPaths: ['checkup.optional.fundusPhoto', 'riskModelExtras.fundusResult'],
  },
  {
    id: 'brain_ct',
    label: '颅脑CT',
    category: 'target_organ',
    referenceRange: '无腔隙性梗死、脑出血或显著白质病变',
    clinicalMeaning: '筛查高血压相关脑血管病变',
    retestCycle: '有神经症状或高危者按需检查',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['brainCtResult'],
    checkupPaths: ['checkup.optional.ct', 'riskModelExtras.brainCtResult'],
  },
  {
    id: 'homocysteine',
    label: '同型半胱氨酸（H型高血压）',
    category: 'target_organ',
    referenceRange: '5–15 μmol/L（因实验室而异）',
    clinicalMeaning: 'H型高血压与卒中风险相关，可考虑叶酸干预',
    retestCycle: '每年（高危人群）',
    isCoreForHypertension: false,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['homocysteine'],
    checkupPaths: ['checkup.labBasic.homocysteine', 'checkup.optional.homocysteine'],
  },
  {
    id: 'lipids',
    label: '血脂全套',
    category: 'metabolic_labs',
    referenceRange: 'LDL-C<2.6 mmol/L（合并ASCVD<1.8）',
    clinicalMeaning: '评估心血管总体风险，指导联合干预',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['tc', 'tg', 'ldl', 'hdl'],
    checkupPaths: [
      'checkup.labBasic.lipids.tc',
      'checkup.labBasic.lipids.tg',
      'checkup.labBasic.lipids.ldl',
      'checkup.labBasic.lipids.hdl',
    ],
  },
  {
    id: 'glucose_hba1c',
    label: '血糖、糖化血红蛋白',
    category: 'metabolic_labs',
    referenceRange: 'FPG<6.1 mmol/L；HbA1c<6.0%',
    clinicalMeaning: '高血压常合并糖代谢异常，需共同管理',
    retestCycle: '每年（糖尿病者每3个月）',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['fastingGlucose', 'hba1c'],
    checkupPaths: [
      'checkup.labBasic.glucose.fasting',
      'checkup.labBasic.hba1c',
      'checkup.optional.hba1c',
    ],
  },
  {
    id: 'electrolytes',
    label: '电解质（钾钠氯钙）',
    category: 'metabolic_labs',
    referenceRange: 'K 3.5–5.5；Na 135–145 mmol/L（因实验室而异）',
    clinicalMeaning: '低钾提示继发性高血压可能；监测利尿剂不良反应',
    retestCycle: '启动/调整降压药后1–4周；稳定后每6–12个月',
    isCoreForHypertension: true,
    priority: 'medium',
    screeningFields: ['potassium', 'sodium', 'chloride', 'calcium'],
    checkupPaths: [
      'riskModelExtras.potassium',
      'riskModelExtras.sodium',
      'riskModelExtras.electrolytesSummary',
    ],
  },
  {
    id: 'raas',
    label: '肾素、血管紧张素、醛固酮（继发性排查）',
    category: 'metabolic_labs',
    referenceRange: '因体位、药物及实验室方法而异',
    clinicalMeaning: '排查原醛、肾血管性高血压等继发性因素',
    retestCycle: '难治性高血压、低钾、年轻患者疑诊时',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['renin', 'angiotensin', 'aldosterone'],
    checkupPaths: [
      'riskModelExtras.renin',
      'riskModelExtras.angiotensin',
      'riskModelExtras.aldosterone',
    ],
  },
];

export const getHypertensionCatalogItem = (id: string) =>
  HYPERTENSION_SCREENING_CATALOG.find((i) => i.id === id);
