import type { HypertensionIndicatorCategoryId } from '../types';
import { EXAM_REFERENCE_TEXT } from './examReportReferenceService';

export interface HypertensionCatalogItem {
  id: string;
  label: string;
  category: HypertensionIndicatorCategoryId;
  referenceRange: string;
  clinicalMeaning: string;
  retestCycle: string;
  isCoreForHypertension: boolean;
  priority: 'high' | 'medium' | 'low';
  unit?: string;
  screeningFields?: (keyof import('../types').HypertensionScreeningRecord)[];
  checkupPaths?: string[];
}

export const HYPERTENSION_INDICATOR_CATEGORIES = [
  { id: 'bp_vascular' as const, label: '血压与血管评估', sortOrder: 1 },
  { id: 'target_organ' as const, label: '靶器官损伤筛查（心脑肾眼）', sortOrder: 2 },
  { id: 'metabolic_labs' as const, label: '代谢与实验室检查', sortOrder: 3 },
];

export const HYPERTENSION_SCREENING_CATALOG: HypertensionCatalogItem[] = [
  {
    id: 'office_bp',
    label: '诊室血压',
    category: 'bp_vascular',
    referenceRange: EXAM_REFERENCE_TEXT.bp,
    clinicalMeaning: '高血压诊断与随访的核心指标',
    retestCycle: '家庭自测每周2–3次；门诊每1–3个月',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmHg',
    screeningFields: ['sbp', 'dbp'],
    checkupPaths: ['checkup.basics.sbp', 'checkup.basics.dbp'],
  },
  {
    id: 'abpm',
    label: '动态血压监测（ABPM）',
    category: 'bp_vascular',
    referenceRange: '24h平均<130/80 mmHg；夜间下降10–20%',
    clinicalMeaning: '识别白大衣高血压、隐匿性高血压及夜间非杓型血压',
    retestCycle: '初诊疑诊时；调整方案后复测',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['abpmSummary', 'abpmDaySbp', 'abpmNightSbp'],
    checkupPaths: ['riskModelExtras.abpmSummary', 'riskModelExtras.abpmDaySbp'],
  },
  {
    id: 'carotid_us',
    label: '颈动脉彩超（斑块、内膜厚度）',
    category: 'bp_vascular',
    referenceRange: 'IMT<1.0 mm（因年龄调整）；无显著斑块',
    clinicalMeaning: '评估大动脉粥样硬化负荷，预测卒中风险',
    retestCycle: '每1–2年（有斑块者缩短）',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['carotidUltrasound', 'carotidImt', 'carotidPlaque'],
    checkupPaths: ['checkup.optional.carotidUltrasound', 'riskModelExtras.carotidImt'],
  },
  {
    id: 'echo',
    label: '心脏彩超（左心室肥厚、心功能）',
    category: 'bp_vascular',
    referenceRange: '无左室肥厚；EF≥50%',
    clinicalMeaning: '筛查高血压性心脏病及心功能受损',
    retestCycle: '每年或方案调整后',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['echoResult', 'lvh', 'ejectionFraction'],
    checkupPaths: ['checkup.optional.heartUltrasound', 'riskModelExtras.echoResult'],
  },
  {
    id: 'ecg',
    label: '心电图',
    category: 'bp_vascular',
    referenceRange: '窦性心律，无显著ST-T异常或左室高电压',
    clinicalMeaning: '筛查左室肥厚、心肌缺血及心律失常',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'medium',
    screeningFields: ['ecgResult'],
    checkupPaths: ['checkup.imagingBasic.ecg'],
  },
  {
    id: 'holter',
    label: '动态心电图（Holter）',
    category: 'bp_vascular',
    referenceRange: '无显著心律失常；无持续ST段改变',
    clinicalMeaning: '发现阵发性心律失常及无症状心肌缺血',
    retestCycle: '有症状或心电图异常时',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['holterResult'],
    checkupPaths: ['riskModelExtras.holterResult'],
  },
  {
    id: 'renal_bun',
    label: '尿素氮(BUN)',
    category: 'target_organ',
    referenceRange: EXAM_REFERENCE_TEXT.bun,
    clinicalMeaning: '评估高血压肾损害及氮质血症',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['urea'],
    checkupPaths: ['checkup.labBasic.renal.urea'],
  },
  {
    id: 'renal_creatinine',
    label: '肌酐(CREA)',
    category: 'target_organ',
    referenceRange: `女 ${EXAM_REFERENCE_TEXT.creatinineFemale}；男 ${EXAM_REFERENCE_TEXT.creatinineMale}`,
    clinicalMeaning: '评估高血压肾损害，可估算 eGFR',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'μmol/L',
    screeningFields: ['creatinine'],
    checkupPaths: ['checkup.labBasic.renal.creatinine'],
  },
  {
    id: 'renal_ua',
    label: '尿酸(UA)',
    category: 'target_organ',
    referenceRange: `女 ${EXAM_REFERENCE_TEXT.uaFemale}；男 ${EXAM_REFERENCE_TEXT.uaMale}`,
    clinicalMeaning: '高尿酸与高血压、心血管风险相关',
    retestCycle: '每年',
    isCoreForHypertension: false,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['uricAcid'],
    checkupPaths: ['checkup.labBasic.renal.ua'],
  },
  {
    id: 'urine_albumin',
    label: '尿微量白蛋白/肌酐比值（UACR）',
    category: 'target_organ',
    referenceRange: 'UACR<30 mg/g',
    clinicalMeaning: '高血压肾损害早期标志',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mg/g',
    screeningFields: ['uacr', 'urineProtein'],
    checkupPaths: ['riskModelExtras.uacr', 'checkup.labBasic.urineRoutine.protein'],
  },
  {
    id: 'fundus',
    label: '眼底检查（高血压眼底病变）',
    category: 'target_organ',
    referenceRange: '无Keith-Wagener III–IV级改变',
    clinicalMeaning: '反映小动脉硬化程度，评估靶器官损害',
    retestCycle: '每年（控制不佳者每6个月）',
    isCoreForHypertension: true,
    priority: 'high',
    screeningFields: ['fundusResult'],
    checkupPaths: ['checkup.optional.fundusPhoto', 'riskModelExtras.fundusResult'],
  },
  {
    id: 'brain_ct',
    label: '颅脑CT',
    category: 'target_organ',
    referenceRange: '无腔隙性梗死、脑出血或显著白质病变',
    clinicalMeaning: '筛查高血压相关脑血管病变',
    retestCycle: '有神经症状或高危者按需检查',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['brainCtResult'],
    checkupPaths: ['checkup.optional.ct', 'riskModelExtras.brainCtResult'],
  },
  {
    id: 'homocysteine',
    label: '同型半胱氨酸（H型高血压）',
    category: 'target_organ',
    referenceRange: EXAM_REFERENCE_TEXT.homocysteine,
    clinicalMeaning: 'H型高血压与卒中风险相关，可考虑叶酸干预',
    retestCycle: '每年（高危人群）',
    isCoreForHypertension: false,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['homocysteine'],
    checkupPaths: ['checkup.labBasic.homocysteine', 'checkup.optional.homocysteine'],
  },
  {
    id: 'lipid_tc',
    label: '总胆固醇(CHOL)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.tc,
    clinicalMeaning: '评估心血管总体风险',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['tc'],
    checkupPaths: ['checkup.labBasic.lipids.tc'],
  },
  {
    id: 'lipid_tg',
    label: '甘油三酯(TG)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.tg,
    clinicalMeaning: '评估心血管及胰腺炎风险',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['tg'],
    checkupPaths: ['checkup.labBasic.lipids.tg'],
  },
  {
    id: 'lipid_hdl',
    label: '高密度脂蛋白(HDL)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.hdl,
    clinicalMeaning: 'HDL 降低提示心血管风险增加',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['hdl'],
    checkupPaths: ['checkup.labBasic.lipids.hdl'],
  },
  {
    id: 'lipid_ldl',
    label: '低密度脂蛋白(LDL)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.ldl,
    clinicalMeaning: 'LDL 是调脂治疗的主要靶点',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['ldl'],
    checkupPaths: ['checkup.labBasic.lipids.ldl'],
  },
  {
    id: 'glucose_fasting',
    label: '空腹血糖',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.glucoseFasting,
    clinicalMeaning: '高血压常合并糖代谢异常，需共同管理',
    retestCycle: '每年',
    isCoreForHypertension: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['fastingGlucose'],
    checkupPaths: ['checkup.labBasic.glucose.fasting'],
  },
  {
    id: 'hba1c',
    label: '糖化血红蛋白(HbA1c)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.hba1c,
    clinicalMeaning: '反映近2–3个月平均血糖',
    retestCycle: '每年（糖尿病者每3个月）',
    isCoreForHypertension: true,
    priority: 'high',
    unit: '%',
    screeningFields: ['hba1c'],
    checkupPaths: ['checkup.labBasic.hba1c', 'checkup.optional.hba1c'],
  },
  {
    id: 'liver_alt',
    label: '谷丙转氨酶(ALT)',
    category: 'metabolic_labs',
    referenceRange: `男 ${EXAM_REFERENCE_TEXT.altMale}；女 ${EXAM_REFERENCE_TEXT.altFemale}`,
    clinicalMeaning: '评估肝功能，监测降压药相关肝损伤',
    retestCycle: '每年',
    isCoreForHypertension: false,
    priority: 'medium',
    unit: 'U/L',
    screeningFields: ['alt'],
    checkupPaths: ['checkup.labBasic.liver.alt'],
  },
  {
    id: 'liver_ast',
    label: '谷草转氨酶(AST)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.ast,
    clinicalMeaning: '评估肝功能',
    retestCycle: '每年',
    isCoreForHypertension: false,
    priority: 'medium',
    unit: 'U/L',
    screeningFields: ['ast'],
    checkupPaths: ['checkup.labBasic.liver.ast'],
  },
  {
    id: 'thyroid_tsh',
    label: '促甲状腺素(TSH)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.tsh,
    clinicalMeaning: '排查甲状腺疾病对血压的影响',
    retestCycle: '难治性高血压或疑诊时',
    isCoreForHypertension: false,
    priority: 'low',
    unit: 'uIU/mL',
    screeningFields: ['tsh'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.tsh'],
  },
  {
    id: 'thyroid_ft3',
    label: '游离三碘甲状腺原氨酸(FT3)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.ft3,
    clinicalMeaning: '甲状腺功能评估',
    retestCycle: '甲功异常时',
    isCoreForHypertension: false,
    priority: 'low',
    unit: 'pmol/L',
    screeningFields: ['ft3'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.t3', 'riskModelExtras.ft3'],
  },
  {
    id: 'thyroid_ft4',
    label: '游离四碘甲状腺原氨酸(FT4)',
    category: 'metabolic_labs',
    referenceRange: EXAM_REFERENCE_TEXT.ft4,
    clinicalMeaning: '甲状腺功能评估',
    retestCycle: '甲功异常时',
    isCoreForHypertension: false,
    priority: 'low',
    unit: 'pmol/L',
    screeningFields: ['ft4'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.t4', 'riskModelExtras.ft4'],
  },
  {
    id: 'electrolytes',
    label: '电解质（钾钠氯钙）',
    category: 'metabolic_labs',
    referenceRange: 'K 3.5–5.5；Na 135–145 mmol/L（因实验室而异）',
    clinicalMeaning: '低钾提示继发性高血压可能；监测利尿剂不良反应',
    retestCycle: '启动/调整降压药后1–4周；稳定后每6–12个月',
    isCoreForHypertension: true,
    priority: 'medium',
    screeningFields: ['potassium', 'sodium', 'chloride', 'calcium'],
    checkupPaths: [
      'riskModelExtras.potassium',
      'riskModelExtras.sodium',
      'riskModelExtras.electrolytesSummary',
    ],
  },
  {
    id: 'raas',
    label: '肾素、血管紧张素、醛固酮（继发性排查）',
    category: 'metabolic_labs',
    referenceRange: '因体位、药物及实验室方法而异',
    clinicalMeaning: '排查原醛、肾血管性高血压等继发性因素',
    retestCycle: '难治性高血压、低钾、年轻患者疑诊时',
    isCoreForHypertension: false,
    priority: 'medium',
    screeningFields: ['renin', 'angiotensin', 'aldosterone'],
    checkupPaths: [
      'riskModelExtras.renin',
      'riskModelExtras.angiotensin',
      'riskModelExtras.aldosterone',
    ],
  },
];

export const getHypertensionCatalogItem = (id: string) =>
  HYPERTENSION_SCREENING_CATALOG.find((i) => i.id === id);
