import type { LipidIndicatorCategoryId } from '../types';

export interface LipidCatalogItem {
  id: string;
  label: string;
  category: LipidIndicatorCategoryId;
  referenceRange: string;
  clinicalMeaning: string;
  retestCycle: string;
  isCoreForLipid: boolean;
  priority: 'high' | 'medium' | 'low';
  unit?: string;
  screeningFields?: (keyof import('../types').LipidScreeningRecord)[];
  checkupPaths?: string[];
}

export const LIPID_INDICATOR_CATEGORIES = [
  { id: 'basic_lipids' as const, label: '基础血脂检测', sortOrder: 1 },
  { id: 'advanced_lipids' as const, label: '进阶脂代谢评估', sortOrder: 2 },
  { id: 'cardiovascular_risk' as const, label: '动脉粥样硬化风险评估', sortOrder: 3 },
  { id: 'metabolic_monitoring' as const, label: '合并症与用药监测', sortOrder: 4 },
  { id: 'secondary_screening' as const, label: '继发性血脂异常排查', sortOrder: 5 },
];

export const LIPID_SCREENING_CATALOG: LipidCatalogItem[] = [
  {
    id: 'lipids_panel',
    label: '血脂四项（TC/TG/LDL-C/HDL-C）',
    category: 'basic_lipids',
    referenceRange: 'LDL-C<3.4 mmol/L；HDL-C 男≥1.0/女≥1.3；TG<1.7；TC<5.2',
    clinicalMeaning: '血脂异常诊断与调脂治疗随访的核心指标',
    retestCycle: '调脂治疗4–12周复测，稳定后每6–12个月',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['tc', 'tg', 'ldl', 'hdl'],
    checkupPaths: [
      'checkup.labBasic.lipids.tc',
      'checkup.labBasic.lipids.tg',
      'checkup.labBasic.lipids.ldl',
      'checkup.labBasic.lipids.hdl',
    ],
  },
  {
    id: 'non_hdl',
    label: '非HDL-C',
    category: 'basic_lipids',
    referenceRange: '非HDL-C<4.1 mmol/L（高危人群更严）',
    clinicalMeaning: '反映含 ApoB 脂蛋白颗粒负荷，高 TG 时优于 LDL 评估',
    retestCycle: '与血脂四项同步',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['nonHdl'],
    checkupPaths: ['riskModelExtras.nonHdl'],
  },
  {
    id: 'apob',
    label: '载脂蛋白 B（ApoB）',
    category: 'advanced_lipids',
    referenceRange: '因实验室而异，一般<1.0 g/L',
    clinicalMeaning: '反映致动脉粥样硬化脂蛋白颗粒数，ASCVD 残余风险评估',
    retestCycle: '高危/调脂未达标者每年',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['apoB'],
    checkupPaths: ['riskModelExtras.apoB', 'checkup.optional.apoB'],
  },
  {
    id: 'lpa',
    label: '脂蛋白(a) [Lp(a)]',
    category: 'advanced_lipids',
    referenceRange: '<300 mg/L 或 <75 nmol/L（方法学相关）',
    clinicalMeaning: '终生性 ASCVD 危险因子，一生检测1–2次即可',
    retestCycle: '终生检测1–2次；特殊治疗随访时复测',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['lpa'],
    checkupPaths: ['riskModelExtras.lpa', 'checkup.optional.lpa'],
  },
  {
    id: 'sdldl',
    label: '小而密 LDL（sdLDL）',
    category: 'advanced_lipids',
    referenceRange: '因实验室而异',
    clinicalMeaning: '更具致动脉粥样硬化性的 LDL 亚型',
    retestCycle: '调脂疗效评估时按需',
    isCoreForLipid: false,
    priority: 'low',
    screeningFields: ['sdLdl'],
    checkupPaths: ['riskModelExtras.sdLdl'],
  },
  {
    id: 'hs_crp',
    label: '超敏 C 反应蛋白（hs-CRP）',
    category: 'cardiovascular_risk',
    referenceRange: '<3 mg/L（低危）；≥3 提示炎症/残余风险',
    clinicalMeaning: '反映低度系统性炎症，辅助 ASCVD 风险分层',
    retestCycle: '每年或方案调整时',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'mg/L',
    screeningFields: ['hsCrp'],
    checkupPaths: ['riskModelExtras.hsCrp', 'checkup.labBasic.hsCrp'],
  },
  {
    id: 'homocysteine',
    label: '同型半胱氨酸',
    category: 'cardiovascular_risk',
    referenceRange: '5–15 μmol/L（因实验室而异）',
    clinicalMeaning: '与 ASCVD 及卒中风险相关，可指导叶酸/B 族维生素干预',
    retestCycle: '每年（高危人群）',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['homocysteine'],
    checkupPaths: ['checkup.labBasic.homocysteine', 'checkup.optional.homocysteine'],
  },
  {
    id: 'carotid_us',
    label: '颈动脉彩超（斑块/IMT）',
    category: 'cardiovascular_risk',
    referenceRange: 'IMT<1.0 mm；无显著斑块',
    clinicalMeaning: '亚临床动脉粥样硬化评估，辅助 ASCVD 危险分层',
    retestCycle: '中高危每1–2年',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['carotidUltrasound', 'carotidImt', 'carotidPlaque'],
    checkupPaths: ['checkup.optional.carotidUltrasound', 'riskModelExtras.carotidImt'],
  },
  {
    id: 'ecg',
    label: '心电图',
    category: 'cardiovascular_risk',
    referenceRange: '窦性心律，无显著 ST-T 异常',
    clinicalMeaning: '筛查心肌缺血及心律失常',
    retestCycle: '每年（ASCVD 高危者）',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['ecgResult'],
    checkupPaths: ['checkup.imagingBasic.ecg'],
  },
  {
    id: 'abi',
    label: '踝臂指数（ABI）/ 动脉硬化',
    category: 'cardiovascular_risk',
    referenceRange: 'ABI 0.9–1.3',
    clinicalMeaning: '筛查外周动脉疾病及动脉硬化负荷',
    retestCycle: '高危或症状时',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['abiSummary', 'leftABI', 'rightABI'],
    checkupPaths: [
      'checkup.optional.arteriosclerosis.leftABI',
      'checkup.optional.arteriosclerosis.rightABI',
    ],
  },
  {
    id: 'glucose_hba1c',
    label: '血糖、糖化血红蛋白',
    category: 'metabolic_monitoring',
    referenceRange: 'FPG<6.1 mmol/L；HbA1c<6.0%',
    clinicalMeaning: '血脂异常常合并糖代谢异常，影响 ASCVD 总体风险',
    retestCycle: '每年（糖尿病者每3个月）',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['fastingGlucose', 'hba1c'],
    checkupPaths: [
      'checkup.labBasic.glucose.fasting',
      'checkup.labBasic.hba1c',
      'checkup.optional.hba1c',
    ],
  },
  {
    id: 'office_bp',
    label: '血压',
    category: 'metabolic_monitoring',
    referenceRange: '一般<140/90 mmHg',
    clinicalMeaning: '高血压与血脂异常同为 ASCVD 主要危险因素',
    retestCycle: '家庭自测每周2–3次；门诊每1–3个月',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmHg',
    screeningFields: ['sbp', 'dbp'],
    checkupPaths: ['checkup.basics.sbp', 'checkup.basics.dbp'],
  },
  {
    id: 'liver_enzymes',
    label: '肝功能（ALT/AST）',
    category: 'metabolic_monitoring',
    referenceRange: '因实验室而异；调脂药监测基线及随访',
    clinicalMeaning: '他汀类药物肝毒性监测；非酒精性脂肪肝评估',
    retestCycle: '调脂启动后4–12周，稳定后每6–12个月',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['alt', 'ast'],
    checkupPaths: ['checkup.labBasic.liver.alt', 'checkup.labBasic.liver.ast'],
  },
  {
    id: 'renal',
    label: '肾功能',
    category: 'metabolic_monitoring',
    referenceRange: 'eGFR≥60 mL/min/1.73m²',
    clinicalMeaning: '慢性肾病为 ASCVD 等危症；影响调脂药选择',
    retestCycle: '每年',
    isCoreForLipid: true,
    priority: 'medium',
    screeningFields: ['creatinine', 'uacr'],
    checkupPaths: ['checkup.labBasic.renal.creatinine', 'riskModelExtras.uacr'],
  },
  {
    id: 'tsh',
    label: '甲状腺功能（TSH）',
    category: 'secondary_screening',
    referenceRange: '因实验室而异',
    clinicalMeaning: '甲状腺功能减退可致继发性血脂升高',
    retestCycle: '初诊血脂异常或难达标时',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['tsh'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.tsh'],
  },
  {
    id: 'urine_protein',
    label: '尿蛋白/尿微量白蛋白',
    category: 'secondary_screening',
    referenceRange: 'UACR<30 mg/g',
    clinicalMeaning: '肾病综合征等可致严重高脂血症',
    retestCycle: '每年或肾病高危者',
    isCoreForLipid: false,
    priority: 'low',
    screeningFields: ['urineProtein', 'uacr'],
    checkupPaths: ['checkup.labBasic.urineRoutine.protein', 'riskModelExtras.uacr'],
  },
];

export const getLipidCatalogItem = (id: string) => LIPID_SCREENING_CATALOG.find((i) => i.id === id);
