import type { LipidIndicatorCategoryId } from '../types';
import { EXAM_REFERENCE_TEXT } from './examReportReferenceService';

export interface LipidCatalogItem {
  id: string;
  label: string;
  category: LipidIndicatorCategoryId;
  referenceRange: string;
  clinicalMeaning: string;
  retestCycle: string;
  isCoreForLipid: boolean;
  priority: 'high' | 'medium' | 'low';
  unit?: string;
  screeningFields?: (keyof import('../types').LipidScreeningRecord)[];
  checkupPaths?: string[];
}

export const LIPID_INDICATOR_CATEGORIES = [
  { id: 'basic_lipids' as const, label: '基础血脂检测', sortOrder: 1 },
  { id: 'advanced_lipids' as const, label: '进阶脂代谢评估', sortOrder: 2 },
  { id: 'cardiovascular_risk' as const, label: '动脉粥样硬化风险评估', sortOrder: 3 },
  { id: 'metabolic_monitoring' as const, label: '合并症与用药监测', sortOrder: 4 },
  { id: 'secondary_screening' as const, label: '继发性血脂异常排查', sortOrder: 5 },
];

export const LIPID_SCREENING_CATALOG: LipidCatalogItem[] = [
  {
    id: 'lipid_tc',
    label: '总胆固醇(CHOL)',
    category: 'basic_lipids',
    referenceRange: EXAM_REFERENCE_TEXT.tc,
    clinicalMeaning: '血脂异常诊断与调脂治疗随访的核心指标',
    retestCycle: '调脂治疗4–12周复测，稳定后每6–12个月',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['tc'],
    checkupPaths: ['checkup.labBasic.lipids.tc'],
  },
  {
    id: 'lipid_tg',
    label: '甘油三酯(TG)',
    category: 'basic_lipids',
    referenceRange: EXAM_REFERENCE_TEXT.tg,
    clinicalMeaning: '高 TG 与胰腺炎及 ASCVD 风险相关',
    retestCycle: '与血脂四项同步',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['tg'],
    checkupPaths: ['checkup.labBasic.lipids.tg'],
  },
  {
    id: 'lipid_hdl',
    label: '高密度脂蛋白(HDL)',
    category: 'basic_lipids',
    referenceRange: EXAM_REFERENCE_TEXT.hdl,
    clinicalMeaning: 'HDL 降低提示 ASCVD 风险增加',
    retestCycle: '与血脂四项同步',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['hdl'],
    checkupPaths: ['checkup.labBasic.lipids.hdl'],
  },
  {
    id: 'lipid_ldl',
    label: '低密度脂蛋白(LDL)',
    category: 'basic_lipids',
    referenceRange: EXAM_REFERENCE_TEXT.ldl,
    clinicalMeaning: '调脂治疗的首要靶点',
    retestCycle: '与血脂四项同步',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['ldl'],
    checkupPaths: ['checkup.labBasic.lipids.ldl'],
  },
  {
    id: 'non_hdl',
    label: '非HDL-C',
    category: 'basic_lipids',
    referenceRange: '非HDL-C<4.1 mmol/L（高危人群更严）',
    clinicalMeaning: '反映含 ApoB 脂蛋白颗粒负荷，高 TG 时优于 LDL 评估',
    retestCycle: '与血脂四项同步',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['nonHdl'],
    checkupPaths: ['riskModelExtras.nonHdl'],
  },
  {
    id: 'apob',
    label: '载脂蛋白 B（ApoB）',
    category: 'advanced_lipids',
    referenceRange: '因实验室而异，一般<1.0 g/L',
    clinicalMeaning: '反映致动脉粥样硬化脂蛋白颗粒数，ASCVD 残余风险评估',
    retestCycle: '高危/调脂未达标者每年',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['apoB'],
    checkupPaths: ['riskModelExtras.apoB', 'checkup.optional.apoB'],
  },
  {
    id: 'lpa',
    label: '脂蛋白(a) [Lp(a)]',
    category: 'advanced_lipids',
    referenceRange: '<300 mg/L 或 <75 nmol/L（方法学相关）',
    clinicalMeaning: '终生性 ASCVD 危险因子，一生检测1–2次即可',
    retestCycle: '终生检测1–2次；特殊治疗随访时复测',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['lpa'],
    checkupPaths: ['riskModelExtras.lpa', 'checkup.optional.lpa'],
  },
  {
    id: 'sdldl',
    label: '小而密 LDL（sdLDL）',
    category: 'advanced_lipids',
    referenceRange: '因实验室而异',
    clinicalMeaning: '更具致动脉粥样硬化性的 LDL 亚型',
    retestCycle: '调脂疗效评估时按需',
    isCoreForLipid: false,
    priority: 'low',
    screeningFields: ['sdLdl'],
    checkupPaths: ['riskModelExtras.sdLdl'],
  },
  {
    id: 'hs_crp',
    label: '超敏 C 反应蛋白（hs-CRP）',
    category: 'cardiovascular_risk',
    referenceRange: '<3 mg/L（低危）；≥3 提示炎症/残余风险',
    clinicalMeaning: '反映低度系统性炎症，辅助 ASCVD 风险分层',
    retestCycle: '每年或方案调整时',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'mg/L',
    screeningFields: ['hsCrp'],
    checkupPaths: ['riskModelExtras.hsCrp', 'checkup.labBasic.hsCrp'],
  },
  {
    id: 'homocysteine',
    label: '同型半胱氨酸',
    category: 'cardiovascular_risk',
    referenceRange: EXAM_REFERENCE_TEXT.homocysteine,
    clinicalMeaning: '与 ASCVD 及卒中风险相关，可指导叶酸/B 族维生素干预',
    retestCycle: '每年（高危人群）',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['homocysteine'],
    checkupPaths: ['checkup.labBasic.homocysteine', 'checkup.optional.homocysteine'],
  },
  {
    id: 'carotid_us',
    label: '颈动脉彩超（斑块/IMT）',
    category: 'cardiovascular_risk',
    referenceRange: 'IMT<1.0 mm；无显著斑块',
    clinicalMeaning: '亚临床动脉粥样硬化评估，辅助 ASCVD 危险分层',
    retestCycle: '中高危每1–2年',
    isCoreForLipid: true,
    priority: 'high',
    screeningFields: ['carotidUltrasound', 'carotidImt', 'carotidPlaque'],
    checkupPaths: ['checkup.optional.carotidUltrasound', 'riskModelExtras.carotidImt'],
  },
  {
    id: 'ecg',
    label: '心电图',
    category: 'cardiovascular_risk',
    referenceRange: '窦性心律，无显著 ST-T 异常',
    clinicalMeaning: '筛查心肌缺血及心律失常',
    retestCycle: '每年（ASCVD 高危者）',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['ecgResult'],
    checkupPaths: ['checkup.imagingBasic.ecg'],
  },
  {
    id: 'abi',
    label: '踝臂指数（ABI）/ 动脉硬化',
    category: 'cardiovascular_risk',
    referenceRange: 'ABI 0.9–1.3',
    clinicalMeaning: '筛查外周动脉疾病及动脉硬化负荷',
    retestCycle: '高危或症状时',
    isCoreForLipid: false,
    priority: 'medium',
    screeningFields: ['abiSummary', 'leftABI', 'rightABI'],
    checkupPaths: [
      'checkup.optional.arteriosclerosis.leftABI',
      'checkup.optional.arteriosclerosis.rightABI',
    ],
  },
  {
    id: 'glucose_fasting',
    label: '空腹血糖',
    category: 'metabolic_monitoring',
    referenceRange: EXAM_REFERENCE_TEXT.glucoseFasting,
    clinicalMeaning: '血脂异常常合并糖代谢异常',
    retestCycle: '每年',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmol/L',
    screeningFields: ['fastingGlucose'],
    checkupPaths: ['checkup.labBasic.glucose.fasting'],
  },
  {
    id: 'hba1c',
    label: '糖化血红蛋白(HbA1c)',
    category: 'metabolic_monitoring',
    referenceRange: EXAM_REFERENCE_TEXT.hba1c,
    clinicalMeaning: '反映近2–3个月平均血糖',
    retestCycle: '每年（糖尿病者每3个月）',
    isCoreForLipid: true,
    priority: 'high',
    unit: '%',
    screeningFields: ['hba1c'],
    checkupPaths: ['checkup.labBasic.hba1c', 'checkup.optional.hba1c'],
  },
  {
    id: 'office_bp',
    label: '血压',
    category: 'metabolic_monitoring',
    referenceRange: EXAM_REFERENCE_TEXT.bp,
    clinicalMeaning: '高血压与血脂异常同为 ASCVD 主要危险因素',
    retestCycle: '家庭自测每周2–3次；门诊每1–3个月',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'mmHg',
    screeningFields: ['sbp', 'dbp'],
    checkupPaths: ['checkup.basics.sbp', 'checkup.basics.dbp'],
  },
  {
    id: 'liver_alt',
    label: '谷丙转氨酶(ALT)',
    category: 'metabolic_monitoring',
    referenceRange: `男 ${EXAM_REFERENCE_TEXT.altMale}；女 ${EXAM_REFERENCE_TEXT.altFemale}`,
    clinicalMeaning: '他汀类药物肝毒性监测',
    retestCycle: '调脂启动后4–12周，稳定后每6–12个月',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'U/L',
    screeningFields: ['alt'],
    checkupPaths: ['checkup.labBasic.liver.alt'],
  },
  {
    id: 'liver_ast',
    label: '谷草转氨酶(AST)',
    category: 'metabolic_monitoring',
    referenceRange: EXAM_REFERENCE_TEXT.ast,
    clinicalMeaning: '他汀类药物肝毒性监测',
    retestCycle: '调脂启动后4–12周，稳定后每6–12个月',
    isCoreForLipid: true,
    priority: 'high',
    unit: 'U/L',
    screeningFields: ['ast'],
    checkupPaths: ['checkup.labBasic.liver.ast'],
  },
  {
    id: 'renal_bun',
    label: '尿素氮(BUN)',
    category: 'metabolic_monitoring',
    referenceRange: EXAM_REFERENCE_TEXT.bun,
    clinicalMeaning: '慢性肾病影响调脂药选择',
    retestCycle: '每年',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'mmol/L',
    screeningFields: ['urea'],
    checkupPaths: ['checkup.labBasic.renal.urea'],
  },
  {
    id: 'renal_creatinine',
    label: '肌酐(CREA)',
    category: 'metabolic_monitoring',
    referenceRange: `女 ${EXAM_REFERENCE_TEXT.creatinineFemale}；男 ${EXAM_REFERENCE_TEXT.creatinineMale}`,
    clinicalMeaning: '评估肾功能，可估算 eGFR',
    retestCycle: '每年',
    isCoreForLipid: true,
    priority: 'medium',
    unit: 'μmol/L',
    screeningFields: ['creatinine'],
    checkupPaths: ['checkup.labBasic.renal.creatinine'],
  },
  {
    id: 'renal_ua',
    label: '尿酸(UA)',
    category: 'metabolic_monitoring',
    referenceRange: `女 ${EXAM_REFERENCE_TEXT.uaFemale}；男 ${EXAM_REFERENCE_TEXT.uaMale}`,
    clinicalMeaning: '高尿酸与代谢综合征相关',
    retestCycle: '每年',
    isCoreForLipid: false,
    priority: 'low',
    unit: 'μmol/L',
    screeningFields: ['uricAcid'],
    checkupPaths: ['checkup.labBasic.renal.ua'],
  },
  {
    id: 'thyroid_tsh',
    label: '促甲状腺素(TSH)',
    category: 'secondary_screening',
    referenceRange: EXAM_REFERENCE_TEXT.tsh,
    clinicalMeaning: '甲状腺功能减退可致继发性血脂升高',
    retestCycle: '初诊血脂异常或难达标时',
    isCoreForLipid: false,
    priority: 'medium',
    unit: 'uIU/mL',
    screeningFields: ['tsh'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.tsh'],
  },
  {
    id: 'thyroid_ft3',
    label: '游离三碘甲状腺原氨酸(FT3)',
    category: 'secondary_screening',
    referenceRange: EXAM_REFERENCE_TEXT.ft3,
    clinicalMeaning: '甲状腺功能评估',
    retestCycle: '甲功异常时',
    isCoreForLipid: false,
    priority: 'low',
    unit: 'pmol/L',
    screeningFields: ['ft3'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.t3', 'riskModelExtras.ft3'],
  },
  {
    id: 'thyroid_ft4',
    label: '游离四碘甲状腺原氨酸(FT4)',
    category: 'secondary_screening',
    referenceRange: EXAM_REFERENCE_TEXT.ft4,
    clinicalMeaning: '甲状腺功能评估',
    retestCycle: '甲功异常时',
    isCoreForLipid: false,
    priority: 'low',
    unit: 'pmol/L',
    screeningFields: ['ft4'],
    checkupPaths: ['checkup.labBasic.thyroidFunction.t4', 'riskModelExtras.ft4'],
  },
  {
    id: 'urine_protein',
    label: '尿蛋白/尿微量白蛋白',
    category: 'secondary_screening',
    referenceRange: 'UACR<30 mg/g',
    clinicalMeaning: '肾病综合征等可致严重高脂血症',
    retestCycle: '每年或肾病高危者',
    isCoreForLipid: false,
    priority: 'low',
    screeningFields: ['urineProtein', 'uacr'],
    checkupPaths: ['checkup.labBasic.urineRoutine.protein', 'riskModelExtras.uacr'],
  },
];

export const getLipidCatalogItem = (id: string) => LIPID_SCREENING_CATALOG.find((i) => i.id === id);
